INSERT INTO snacks (snack, name, description, price, image, createdAt, updatedAt)
VALUES
  ('burger', 'Mega', 'O artesanal tamanho família recheado com três carnes suculentas, queijo e bacon.', 25.5, 'https://i.imgur.com/upjIUnG.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('burger', 'Extra Bacon', 'Criado para os amantes de bacon, possui em todas as suas camadas bacon bem assado e ainda queijo e carne.', 23.5, 'https://i.imgur.com/B4J04AJ.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('burger', 'Tradicional', 'O simples também é delicioso, principalmente se envolver nossa carne artesanal e queijo.', 12, 'https://i.imgur.com/Jz506jB.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('burger', 'Big Carne', 'Uma carne artesanal de primeira qualidade com 4cm de altura e uma salada completa com alface, cebola, tomate e outros.', 18, 'https://i.imgur.com/bF8EdBb.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('burger', 'Carne dupla', 'Já pensou em comer aquele sanduíche com carne dupla e saborosa, recheada com queijo, molho e salada? Então você pensou exatamente nesse hambúrguer.', 20, 'https://i.imgur.com/fdEY2kY.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Calabresa', 'Pizza recheada com calabresa, cebola, mussarela, orégano e azeitona, tendo uma borda recheada com catupiry.', 25, 'https://i.imgur.com/5rjJGkV.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Portuguesa', 'Pizza recheada com presunto, mussarela, ovo, cebola, azeitona, orégano, tomate e molho de tomate, tendo uma borda recheada com catupiry.', 28.5, 'https://i.imgur.com/WCoyGoI.png', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Frango com Catupiry', 'Pizza recheada com frango, catupiry e brócolis, tendo uma borda recheada com catupiry.', 24, 'https://i.imgur.com/BuXrO8d.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Napolitana', 'Pizza recheada com queijo, mussarela, tomate e couve, tendo uma borda recheada com catupiry.', 30, 'https://i.imgur.com/u3DfvCE.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Mussarela', 'Pizza recheada com mussarela, tendo uma borda recheada com catupiry. ', 20.5, 'https://i.imgur.com/kPNXpa0.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Marguerita', 'Pizza recheada com calabresa, mussarela, cebola, azeitona e orégano, tendo uma borda recheada com catupiry.', 25.5, 'https://i.imgur.com/AsEfsZN.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Brigadeiro com Morango', 'Pizza doce recheada com brigadeiro e morango.', 35, 'https://i.imgur.com/43yC2Ap.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Banana', 'Pizza doce recheada com banana e leite condensado.', 33.5, 'https://i.imgur.com/Pcrgg1P.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('pizza', 'Chocolate', 'Pizza doce recheada com chocolate e bolinhas de chocolate.', 30, 'https://i.imgur.com/RahAKkH.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('drink', 'Coca-Cola 2L', 'A tradicional Coca-Cola que a família brasileira adora.', 12, 'https://i.imgur.com/Lg3aKhf.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('drink', 'Guaraná Antarctica', 'O irresistível e saboroso Guaraná Antarctica em sua versão de latinha.', 6.5, 'https://i.imgur.com/hOBrOIm.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('drink', 'Suco de Abacaxi', 'Suco natural de abacaxi com leves incrementos de algumas hortaliças para fortificar sua saúde.', 8, 'https://i.imgur.com/VV9qTMh.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('drink', 'Suco de Laranja', 'Suco natural de laranja para você que é amante dessa fruta.', 8, 'https://i.imgur.com/2Lf2gHy.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('ice-cream', 'Casquinha', 'A casquinha crocante e saborosa que nossos clientes amam.', 4.5, 'https://i.imgur.com/YGmeoCm.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('ice-cream', 'Chocolate com granulado', 'Sorvete de chocolate com granulados em chocolate para você se deliciar.', 6, 'https://i.imgur.com/osAHOLe.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('ice-cream', 'Flocos', 'O tradicional flocos vem com cobertura em chocolate para adocicar seu dia.', 7, 'https://i.imgur.com/qgnFLiy.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('ice-cream', 'Creme', 'O simples sorvete de creme com um gosto irresistível.', 6.5, 'https://i.imgur.com/dFLysrT.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
  ('ice-cream', 'Morango', 'O clássico sorvete de morango que deixe tudo mais leve.', 10, 'https://i.imgur.com/0TWnEI7.jpg', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6));
